(* autogenerated from github.com/goose-lang/goose/testdata/examples/channel/map_reduce/leaky_buffer *)
From New.golang Require Import defn.
Module pkg_id.
Definition leakbuffer : go_string := "github.com/goose-lang/goose/testdata/examples/channel/map_reduce/leaky_buffer".

End pkg_id.
Export pkg_id.
Module leakbuffer.

Definition LeakyBuffer {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "github.com/goose-lang/goose/testdata/examples/channel/map_reduce/leaky_buffer.LeakyBuffer"%go [].

Definition NewLeakyBuffer {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/goose-lang/goose/testdata/examples/channel/map_reduce/leaky_buffer.NewLeakyBuffer"%go.

(* NewLeakyBuffer creates a LeakyBuffer with:
   - maxFree: max number of buffers kept for reuse
   - bufCap: capacity of each buffer
   - serverChan: channel used to hand off full buffers to the server.

   go: leaky_buffer.go:25:6 *)
Definition NewLeakyBufferⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "maxFree" "maxInflight" "bufCap",
    exception_do (let: "bufCap" := (GoAlloc go.int "bufCap") in
    let: "maxInflight" := (GoAlloc go.int "maxInflight") in
    let: "maxFree" := (GoAlloc go.int "maxFree") in
    return: (GoAlloc LeakyBuffer (let: "$v0" := ((FuncResolve go.make2 [go.ChannelType go.sendrecv (go.SliceType go.byte)] #()) (![go.int] "maxInflight")) in
     let: "$v1" := ((FuncResolve go.make2 [go.ChannelType go.sendrecv (go.SliceType go.byte)] #()) (![go.int] "maxFree")) in
     let: "$v2" := (![go.int] "bufCap") in
     CompositeLiteral LeakyBuffer (LiteralValue [KeyedElement (Some (KeyField "serverChan"%go)) (ElementExpression (go.ChannelType go.sendrecv (go.SliceType go.byte)) "$v0"); KeyedElement (Some (KeyField "free"%go)) (ElementExpression (go.ChannelType go.sendrecv (go.SliceType go.byte)) "$v1"); KeyedElement (Some (KeyField "bufCap"%go)) (ElementExpression go.int "$v2")])))).

(* ServerChan exposes the send-only server channel so callers can select on sends.

   go: leaky_buffer.go:34:24 *)
Definition LeakyBuffer__ServerChanⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "lb" <>,
    exception_do (let: "lb" := (GoAlloc (go.PointerType LeakyBuffer) "lb") in
    return: (Convert (go.ChannelType go.sendrecv (go.SliceType go.byte)) (go.ChannelType go.sendonly (go.SliceType go.byte)) (![go.ChannelType go.sendrecv (go.SliceType go.byte)] (StructFieldRef LeakyBuffer "serverChan"%go (![go.PointerType LeakyBuffer] "lb"))))).

(* Acquire returns a buffer with len=0 and cap=lb.bufCap.
   It never blocks: reuse if available, else allocate.

   go: leaky_buffer.go:40:24 *)
Definition LeakyBuffer__Acquireⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "lb" <>,
    exception_do (let: "lb" := (GoAlloc (go.PointerType LeakyBuffer) "lb") in
    let: "$ch0" := (![go.ChannelType go.sendrecv (go.SliceType go.byte)] (StructFieldRef LeakyBuffer "free"%go (![go.PointerType LeakyBuffer] "lb"))) in
    SelectStmt (SelectStmtClauses (Some (return: ((FuncResolve go.make3 [go.SliceType go.byte] #()) #(W64 0) (![go.int] (StructFieldRef LeakyBuffer "bufCap"%go (![go.PointerType LeakyBuffer] "lb")))))) [(CommClause (RecvCase (go.SliceType go.byte) "$ch0") (let: "b" := (GoAlloc (go.SliceType go.byte) (GoZeroVal (go.SliceType go.byte) #())) in
    let: "$r0" := (Fst "$recvVal") in
    do:  ("b" <-[go.SliceType go.byte] "$r0");;;
    return: (let: "$s" := (![go.SliceType go.byte] "b") in
     Slice (go.SliceType go.byte) ("$s", #(W64 0), #(W64 0)))))])).

(* Release attempts to return the buffer to the freelist.
   It never blocks: if freelist is full, the buffer is dropped ("leaky").

   go: leaky_buffer.go:51:24 *)
Definition LeakyBuffer__TryReleaseⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "lb" "b",
    exception_do (let: "lb" := (GoAlloc (go.PointerType LeakyBuffer) "lb") in
    let: "b" := (GoAlloc (go.SliceType go.byte) "b") in
    let: "$v0" := (![go.SliceType go.byte] "b") in
    let: "$ch0" := (![go.ChannelType go.sendrecv (go.SliceType go.byte)] (StructFieldRef LeakyBuffer "free"%go (![go.PointerType LeakyBuffer] "lb"))) in
    SelectStmt (SelectStmtClauses (Some (do:  #())) [(CommClause (SendCase (go.SliceType go.byte) "$ch0" "$v0") (do:  #()))]);;;
    return: #()).

#[global] Instance info' : PkgInfo pkg_id.leakbuffer :=
{|
  pkg_imported_pkgs := []
|}.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.leakbuffer (λ: <>,
      exception_do (do:  #())
      ).

Module LeakyBuffer.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
  serverChan' : chan.t;
  free' : chan.t;
  bufCap' : w64;
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk (zero_val _) (zero_val _) (zero_val _)|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.

End LeakyBuffer.

Definition LeakyBuffer'fds_unsealed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : list go.field_decl := [
  (go.FieldDecl "serverChan"%go (go.ChannelType go.sendrecv (go.SliceType go.byte)));
  (go.FieldDecl "free"%go (go.ChannelType go.sendrecv (go.SliceType go.byte)));
  (go.FieldDecl "bufCap"%go go.int)
].
Program Definition LeakyBuffer'fds {ext : ffi_syntax} {go_gctx : GoGlobalContext} := sealed (LeakyBuffer'fds_unsealed).
Global Instance equals_unfold_LeakyBuffer {ext : ffi_syntax} {go_gctx : GoGlobalContext} : LeakyBuffer'fds =→ LeakyBuffer'fds_unsealed.
Proof. rewrite /LeakyBuffer'fds seal_eq //. Qed.

Definition LeakyBufferⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType (LeakyBuffer'fds).

Class LeakyBuffer_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] LeakyBuffer_type_repr  :: go.TypeReprUnderlying LeakyBufferⁱᵐᵖˡ LeakyBuffer.t;
  #[global] LeakyBuffer_underlying :: (LeakyBuffer) <u (LeakyBufferⁱᵐᵖˡ);
  #[global] LeakyBuffer_get_serverChan (x : LeakyBuffer.t) :: ⟦StructFieldGet (LeakyBufferⁱᵐᵖˡ) "serverChan", #x⟧ ⤳[under] #x.(LeakyBuffer.serverChan');
  #[global] LeakyBuffer_set_serverChan (x : LeakyBuffer.t) y :: ⟦StructFieldSet (LeakyBufferⁱᵐᵖˡ) "serverChan", (#x, #y)⟧ ⤳[under] #(x <|LeakyBuffer.serverChan' := y|>);
  #[global] LeakyBuffer_get_free (x : LeakyBuffer.t) :: ⟦StructFieldGet (LeakyBufferⁱᵐᵖˡ) "free", #x⟧ ⤳[under] #x.(LeakyBuffer.free');
  #[global] LeakyBuffer_set_free (x : LeakyBuffer.t) y :: ⟦StructFieldSet (LeakyBufferⁱᵐᵖˡ) "free", (#x, #y)⟧ ⤳[under] #(x <|LeakyBuffer.free' := y|>);
  #[global] LeakyBuffer_get_bufCap (x : LeakyBuffer.t) :: ⟦StructFieldGet (LeakyBufferⁱᵐᵖˡ) "bufCap", #x⟧ ⤳[under] #x.(LeakyBuffer.bufCap');
  #[global] LeakyBuffer_set_bufCap (x : LeakyBuffer.t) y :: ⟦StructFieldSet (LeakyBufferⁱᵐᵖˡ) "bufCap", (#x, #y)⟧ ⤳[under] #(x <|LeakyBuffer.bufCap' := y|>);
  #[global] LeakyBuffer'ptr_Acquire_unfold :: MethodUnfold (go.PointerType (LeakyBuffer)) "Acquire" (LeakyBuffer__Acquireⁱᵐᵖˡ);
  #[global] LeakyBuffer'ptr_ServerChan_unfold :: MethodUnfold (go.PointerType (LeakyBuffer)) "ServerChan" (LeakyBuffer__ServerChanⁱᵐᵖˡ);
  #[global] LeakyBuffer'ptr_TryRelease_unfold :: MethodUnfold (go.PointerType (LeakyBuffer)) "TryRelease" (LeakyBuffer__TryReleaseⁱᵐᵖˡ);
}.

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] LeakyBuffer_instance :: LeakyBuffer_Assumptions;
  #[global] NewLeakyBuffer_unfold :: FuncUnfold NewLeakyBuffer [] (NewLeakyBufferⁱᵐᵖˡ);
}.
End leakbuffer.
