(* autogenerated from github.com/tchajed/goose/internal/examples/trust_import *)
From Perennial.goose_lang Require Import prelude.
From Perennial.goose_lang.trusted Require Import github_dot_com.tchajed.goose.internal.examples.trust__import.trusted__example.

Section code.
Context `{ext_ty: ext_types}.
Local Coercion Var' s: expr := Var s.

Definition Bar: val :=
  rec: "Bar" <> :=
    trusted_example.Foo #();;
    #().

End code.
