(* autogenerated from rfc1813 *)
From Perennial.go_lang Require Import prelude.

(* disk FFI *)
From Perennial.go_lang Require Import ffi.disk_prelude.

Definition PROGRAM : expr := #(U32 100003).

Definition VERSION : expr := #(U32 3).

Definition NFS3_FHSIZE : expr := #(U32 64).

Definition NFS3_COOKIEVERFSIZE : expr := #(U32 8).

Definition NFS3_CREATEVERFSIZE : expr := #(U32 8).

Definition NFS3_WRITEVERFSIZE : expr := #(U32 8).

Definition Uint64: ty := uint64T.

Definition Uint32: ty := uint32T.

Definition Filename3: ty := stringT.

Definition Nfspath3: ty := stringT.

Definition Fileid3: ty := Uint64.

Definition Cookie3: ty := Uint64.

Definition Cookieverf3: ty := arrayT byteT.

Definition Createverf3: ty := arrayT byteT.

Definition Writeverf3: ty := arrayT byteT.

Definition Uid3: ty := Uint32.

Definition Gid3: ty := Uint32.

Definition Size3: ty := Uint64.

Definition Offset3: ty := Uint64.

Definition Mode3: ty := Uint32.

Definition Count3: ty := Uint32.

Definition Nfsstat3: ty := uint32T.

Definition NFS3_OK : expr := #0.

Definition NFS3ERR_PERM : expr := #1.

Definition NFS3ERR_NOENT : expr := #2.

Definition NFS3ERR_IO : expr := #5.

Definition NFS3ERR_NXIO : expr := #6.

Definition NFS3ERR_ACCES : expr := #13.

Definition NFS3ERR_EXIST : expr := #17.

Definition NFS3ERR_XDEV : expr := #18.

Definition NFS3ERR_NODEV : expr := #19.

Definition NFS3ERR_NOTDIR : expr := #20.

Definition NFS3ERR_ISDIR : expr := #21.

Definition NFS3ERR_INVAL : expr := #22.

Definition NFS3ERR_FBIG : expr := #27.

Definition NFS3ERR_NOSPC : expr := #28.

Definition NFS3ERR_ROFS : expr := #30.

Definition NFS3ERR_MLINK : expr := #31.

Definition NFS3ERR_NAMETOOLONG : expr := #63.

Definition NFS3ERR_NOTEMPTY : expr := #66.

Definition NFS3ERR_DQUOT : expr := #69.

Definition NFS3ERR_STALE : expr := #70.

Definition NFS3ERR_REMOTE : expr := #71.

Definition NFS3ERR_BADHANDLE : expr := #10001.

Definition NFS3ERR_NOT_SYNC : expr := #10002.

Definition NFS3ERR_BAD_COOKIE : expr := #10003.

Definition NFS3ERR_NOTSUPP : expr := #10004.

Definition NFS3ERR_TOOSMALL : expr := #10005.

Definition NFS3ERR_SERVERFAULT : expr := #10006.

Definition NFS3ERR_BADTYPE : expr := #10007.

Definition NFS3ERR_JUKEBOX : expr := #10008.

Definition Ftype3: ty := uint32T.

Definition NF3REG : expr := #1.

Definition NF3DIR : expr := #2.

Definition NF3BLK : expr := #3.

Definition NF3CHR : expr := #4.

Definition NF3LNK : expr := #5.

Definition NF3SOCK : expr := #6.

Definition NF3FIFO : expr := #7.

Module Specdata3.
  Definition S := struct.decl [
    "Specdata1" :: Uint32;
    "Specdata2" :: Uint32
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Specdata3.

Module Nfs_fh3.
  Definition S := struct.decl [
    "Data" :: slice.T byteT
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Nfs_fh3.

Module Nfstime3.
  Definition S := struct.decl [
    "Seconds" :: Uint32;
    "Nseconds" :: Uint32
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Nfstime3.

Module Fattr3.
  Definition S := struct.decl [
    "Ftype" :: Ftype3;
    "Mode" :: Mode3;
    "Nlink" :: Uint32;
    "Uid" :: Uid3;
    "Gid" :: Gid3;
    "Size" :: Size3;
    "Used" :: Size3;
    "Rdev" :: Specdata3.T;
    "Fsid" :: Uint64;
    "Fileid" :: Fileid3;
    "Atime" :: Nfstime3.T;
    "Mtime" :: Nfstime3.T;
    "Ctime" :: Nfstime3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Fattr3.

Module Post_op_attr.
  Definition S := struct.decl [
    "Attributes_follow" :: boolT;
    "Attributes" :: Fattr3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Post_op_attr.

Module Wcc_attr.
  Definition S := struct.decl [
    "Size" :: Size3;
    "Mtime" :: Nfstime3.T;
    "Ctime" :: Nfstime3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Wcc_attr.

Module Pre_op_attr.
  Definition S := struct.decl [
    "Attributes_follow" :: boolT;
    "Attributes" :: Wcc_attr.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Pre_op_attr.

Module Wcc_data.
  Definition S := struct.decl [
    "Before" :: Pre_op_attr.T;
    "After" :: Post_op_attr.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Wcc_data.

Module Post_op_fh3.
  Definition S := struct.decl [
    "Handle_follows" :: boolT;
    "Handle" :: Nfs_fh3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Post_op_fh3.

Definition Time_how: ty := uint32T.

Definition DONT_CHANGE : expr := #0.

Definition SET_TO_SERVER_TIME : expr := #1.

Definition SET_TO_CLIENT_TIME : expr := #2.

Module Set_mode3.
  Definition S := struct.decl [
    "Set_it" :: boolT;
    "Mode" :: Mode3
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Set_mode3.

Module Set_uid3.
  Definition S := struct.decl [
    "Set_it" :: boolT;
    "Uid" :: Uid3
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Set_uid3.

Module Set_gid3.
  Definition S := struct.decl [
    "Set_it" :: boolT;
    "Gid" :: Gid3
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Set_gid3.

Module Set_size3.
  Definition S := struct.decl [
    "Set_it" :: boolT;
    "Size" :: Size3
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Set_size3.

Module Set_atime.
  Definition S := struct.decl [
    "Set_it" :: Time_how;
    "Atime" :: Nfstime3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Set_atime.

Module Set_mtime.
  Definition S := struct.decl [
    "Set_it" :: Time_how;
    "Mtime" :: Nfstime3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Set_mtime.

Module Sattr3.
  Definition S := struct.decl [
    "Mode" :: Set_mode3.T;
    "Uid" :: Set_uid3.T;
    "Gid" :: Set_gid3.T;
    "Size" :: Set_size3.T;
    "Atime" :: Set_atime.T;
    "Mtime" :: Set_mtime.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Sattr3.

Module Diropargs3.
  Definition S := struct.decl [
    "Dir" :: Nfs_fh3.T;
    "Name" :: Filename3
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Diropargs3.

Definition NFS_PROGRAM : expr := #(U32 100003).

Definition NFS_V3 : expr := #(U32 3).

Definition NFSPROC3_NULL : expr := #(U32 0).

Definition NFSPROC3_GETATTR : expr := #(U32 1).

Definition NFSPROC3_SETATTR : expr := #(U32 2).

Definition NFSPROC3_LOOKUP : expr := #(U32 3).

Definition NFSPROC3_ACCESS : expr := #(U32 4).

Definition NFSPROC3_READLINK : expr := #(U32 5).

Definition NFSPROC3_READ : expr := #(U32 6).

Definition NFSPROC3_WRITE : expr := #(U32 7).

Definition NFSPROC3_CREATE : expr := #(U32 8).

Definition NFSPROC3_MKDIR : expr := #(U32 9).

Definition NFSPROC3_SYMLINK : expr := #(U32 10).

Definition NFSPROC3_MKNOD : expr := #(U32 11).

Definition NFSPROC3_REMOVE : expr := #(U32 12).

Definition NFSPROC3_RMDIR : expr := #(U32 13).

Definition NFSPROC3_RENAME : expr := #(U32 14).

Definition NFSPROC3_LINK : expr := #(U32 15).

Definition NFSPROC3_READDIR : expr := #(U32 16).

Definition NFSPROC3_READDIRPLUS : expr := #(U32 17).

Definition NFSPROC3_FSSTAT : expr := #(U32 18).

Definition NFSPROC3_FSINFO : expr := #(U32 19).

Definition NFSPROC3_PATHCONF : expr := #(U32 20).

Definition NFSPROC3_COMMIT : expr := #(U32 21).

Module GETATTR3args.
  Definition S := struct.decl [
    "Object" :: Nfs_fh3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End GETATTR3args.

Module GETATTR3resok.
  Definition S := struct.decl [
    "Obj_attributes" :: Fattr3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End GETATTR3resok.

Module GETATTR3res.
  Definition S := struct.decl [
    "Status" :: Nfsstat3;
    "Resok" :: GETATTR3resok.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End GETATTR3res.

Module Sattrguard3.
  Definition S := struct.decl [
    "Check" :: boolT;
    "Obj_ctime" :: Nfstime3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Sattrguard3.

Module SETATTR3args.
  Definition S := struct.decl [
    "Object" :: Nfs_fh3.T;
    "New_attributes" :: Sattr3.T;
    "Guard" :: Sattrguard3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End SETATTR3args.

Module SETATTR3resok.
  Definition S := struct.decl [
    "Obj_wcc" :: Wcc_data.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End SETATTR3resok.

Module SETATTR3resfail.
  Definition S := struct.decl [
    "Obj_wcc" :: Wcc_data.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End SETATTR3resfail.

Module SETATTR3res.
  Definition S := struct.decl [
    "Status" :: Nfsstat3;
    "Resok" :: SETATTR3resok.T;
    "Resfail" :: SETATTR3resfail.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End SETATTR3res.

Module LOOKUP3args.
  Definition S := struct.decl [
    "What" :: Diropargs3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End LOOKUP3args.

Module LOOKUP3resok.
  Definition S := struct.decl [
    "Object" :: Nfs_fh3.T;
    "Obj_attributes" :: Post_op_attr.T;
    "Dir_attributes" :: Post_op_attr.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End LOOKUP3resok.

Module LOOKUP3resfail.
  Definition S := struct.decl [
    "Dir_attributes" :: Post_op_attr.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End LOOKUP3resfail.

Module LOOKUP3res.
  Definition S := struct.decl [
    "Status" :: Nfsstat3;
    "Resok" :: LOOKUP3resok.T;
    "Resfail" :: LOOKUP3resfail.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End LOOKUP3res.

Definition ACCESS3_READ : expr := #(U32 1).

Definition ACCESS3_LOOKUP : expr := #(U32 2).

Definition ACCESS3_MODIFY : expr := #(U32 4).

Definition ACCESS3_EXTEND : expr := #(U32 8).

Definition ACCESS3_DELETE : expr := #(U32 16).

Definition ACCESS3_EXECUTE : expr := #(U32 32).

Module ACCESS3args.
  Definition S := struct.decl [
    "Object" :: Nfs_fh3.T;
    "Access" :: Uint32
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End ACCESS3args.

Module ACCESS3resok.
  Definition S := struct.decl [
    "Obj_attributes" :: Post_op_attr.T;
    "Access" :: Uint32
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End ACCESS3resok.

Module ACCESS3resfail.
  Definition S := struct.decl [
    "Obj_attributes" :: Post_op_attr.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End ACCESS3resfail.

Module ACCESS3res.
  Definition S := struct.decl [
    "Status" :: Nfsstat3;
    "Resok" :: ACCESS3resok.T;
    "Resfail" :: ACCESS3resfail.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End ACCESS3res.

Module READLINK3args.
  Definition S := struct.decl [
    "Symlink" :: Nfs_fh3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End READLINK3args.

Module READLINK3resok.
  Definition S := struct.decl [
    "Symlink_attributes" :: Post_op_attr.T;
    "Data" :: Nfspath3
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End READLINK3resok.

Module READLINK3resfail.
  Definition S := struct.decl [
    "Symlink_attributes" :: Post_op_attr.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End READLINK3resfail.

Module READLINK3res.
  Definition S := struct.decl [
    "Status" :: Nfsstat3;
    "Resok" :: READLINK3resok.T;
    "Resfail" :: READLINK3resfail.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End READLINK3res.

Module READ3args.
  Definition S := struct.decl [
    "File" :: Nfs_fh3.T;
    "Offset" :: Offset3;
    "Count" :: Count3
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End READ3args.

Module READ3resok.
  Definition S := struct.decl [
    "File_attributes" :: Post_op_attr.T;
    "Count" :: Count3;
    "Eof" :: boolT;
    "Data" :: slice.T byteT
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End READ3resok.

Module READ3resfail.
  Definition S := struct.decl [
    "File_attributes" :: Post_op_attr.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End READ3resfail.

Module READ3res.
  Definition S := struct.decl [
    "Status" :: Nfsstat3;
    "Resok" :: READ3resok.T;
    "Resfail" :: READ3resfail.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End READ3res.

Definition Stable_how: ty := uint32T.

Definition UNSTABLE : expr := #0.

Definition DATA_SYNC : expr := #1.

Definition FILE_SYNC : expr := #2.

Module WRITE3args.
  Definition S := struct.decl [
    "File" :: Nfs_fh3.T;
    "Offset" :: Offset3;
    "Count" :: Count3;
    "Stable" :: Stable_how;
    "Data" :: slice.T byteT
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End WRITE3args.

Module WRITE3resok.
  Definition S := struct.decl [
    "File_wcc" :: Wcc_data.T;
    "Count" :: Count3;
    "Committed" :: Stable_how;
    "Verf" :: Writeverf3
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End WRITE3resok.

Module WRITE3resfail.
  Definition S := struct.decl [
    "File_wcc" :: Wcc_data.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End WRITE3resfail.

Module WRITE3res.
  Definition S := struct.decl [
    "Status" :: Nfsstat3;
    "Resok" :: WRITE3resok.T;
    "Resfail" :: WRITE3resfail.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End WRITE3res.

Definition Createmode3: ty := uint32T.

Definition UNCHECKED : expr := #0.

Definition GUARDED : expr := #1.

Definition EXCLUSIVE : expr := #2.

Module Createhow3.
  Definition S := struct.decl [
    "Mode" :: Createmode3;
    "Obj_attributes" :: Sattr3.T;
    "Verf" :: Createverf3
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Createhow3.

Module CREATE3args.
  Definition S := struct.decl [
    "Where" :: Diropargs3.T;
    "How" :: Createhow3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End CREATE3args.

Module CREATE3resok.
  Definition S := struct.decl [
    "Obj" :: Post_op_fh3.T;
    "Obj_attributes" :: Post_op_attr.T;
    "Dir_wcc" :: Wcc_data.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End CREATE3resok.

Module CREATE3resfail.
  Definition S := struct.decl [
    "Dir_wcc" :: Wcc_data.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End CREATE3resfail.

Module CREATE3res.
  Definition S := struct.decl [
    "Status" :: Nfsstat3;
    "Resok" :: CREATE3resok.T;
    "Resfail" :: CREATE3resfail.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End CREATE3res.

Module MKDIR3args.
  Definition S := struct.decl [
    "Where" :: Diropargs3.T;
    "Attributes" :: Sattr3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End MKDIR3args.

Module MKDIR3resok.
  Definition S := struct.decl [
    "Obj" :: Post_op_fh3.T;
    "Obj_attributes" :: Post_op_attr.T;
    "Dir_wcc" :: Wcc_data.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End MKDIR3resok.

Module MKDIR3resfail.
  Definition S := struct.decl [
    "Dir_wcc" :: Wcc_data.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End MKDIR3resfail.

Module MKDIR3res.
  Definition S := struct.decl [
    "Status" :: Nfsstat3;
    "Resok" :: MKDIR3resok.T;
    "Resfail" :: MKDIR3resfail.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End MKDIR3res.

Module Symlinkdata3.
  Definition S := struct.decl [
    "Symlink_attributes" :: Sattr3.T;
    "Symlink_data" :: Nfspath3
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Symlinkdata3.

Module SYMLINK3args.
  Definition S := struct.decl [
    "Where" :: Diropargs3.T;
    "Symlink" :: Symlinkdata3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End SYMLINK3args.

Module SYMLINK3resok.
  Definition S := struct.decl [
    "Obj" :: Post_op_fh3.T;
    "Obj_attributes" :: Post_op_attr.T;
    "Dir_wcc" :: Wcc_data.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End SYMLINK3resok.

Module SYMLINK3resfail.
  Definition S := struct.decl [
    "Dir_wcc" :: Wcc_data.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End SYMLINK3resfail.

Module SYMLINK3res.
  Definition S := struct.decl [
    "Status" :: Nfsstat3;
    "Resok" :: SYMLINK3resok.T;
    "Resfail" :: SYMLINK3resfail.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End SYMLINK3res.

Module Devicedata3.
  Definition S := struct.decl [
    "Dev_attributes" :: Sattr3.T;
    "Spec" :: Specdata3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Devicedata3.

Module Mknoddata3.
  Definition S := struct.decl [
    "Ftype" :: Ftype3;
    "Device" :: Devicedata3.T;
    "Pipe_attributes" :: Sattr3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Mknoddata3.

Module MKNOD3args.
  Definition S := struct.decl [
    "Where" :: Diropargs3.T;
    "What" :: Mknoddata3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End MKNOD3args.

Module MKNOD3resok.
  Definition S := struct.decl [
    "Obj" :: Post_op_fh3.T;
    "Obj_attributes" :: Post_op_attr.T;
    "Dir_wcc" :: Wcc_data.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End MKNOD3resok.

Module MKNOD3resfail.
  Definition S := struct.decl [
    "Dir_wcc" :: Wcc_data.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End MKNOD3resfail.

Module MKNOD3res.
  Definition S := struct.decl [
    "Status" :: Nfsstat3;
    "Resok" :: MKNOD3resok.T;
    "Resfail" :: MKNOD3resfail.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End MKNOD3res.

Module REMOVE3args.
  Definition S := struct.decl [
    "Object" :: Diropargs3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End REMOVE3args.

Module REMOVE3resok.
  Definition S := struct.decl [
    "Dir_wcc" :: Wcc_data.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End REMOVE3resok.

Module REMOVE3resfail.
  Definition S := struct.decl [
    "Dir_wcc" :: Wcc_data.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End REMOVE3resfail.

Module REMOVE3res.
  Definition S := struct.decl [
    "Status" :: Nfsstat3;
    "Resok" :: REMOVE3resok.T;
    "Resfail" :: REMOVE3resfail.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End REMOVE3res.

Module RMDIR3args.
  Definition S := struct.decl [
    "Object" :: Diropargs3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End RMDIR3args.

Module RMDIR3resok.
  Definition S := struct.decl [
    "Dir_wcc" :: Wcc_data.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End RMDIR3resok.

Module RMDIR3resfail.
  Definition S := struct.decl [
    "Dir_wcc" :: Wcc_data.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End RMDIR3resfail.

Module RMDIR3res.
  Definition S := struct.decl [
    "Status" :: Nfsstat3;
    "Resok" :: RMDIR3resok.T;
    "Resfail" :: RMDIR3resfail.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End RMDIR3res.

Module RENAME3args.
  Definition S := struct.decl [
    "From" :: Diropargs3.T;
    "To" :: Diropargs3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End RENAME3args.

Module RENAME3resok.
  Definition S := struct.decl [
    "Fromdir_wcc" :: Wcc_data.T;
    "Todir_wcc" :: Wcc_data.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End RENAME3resok.

Module RENAME3resfail.
  Definition S := struct.decl [
    "Fromdir_wcc" :: Wcc_data.T;
    "Todir_wcc" :: Wcc_data.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End RENAME3resfail.

Module RENAME3res.
  Definition S := struct.decl [
    "Status" :: Nfsstat3;
    "Resok" :: RENAME3resok.T;
    "Resfail" :: RENAME3resfail.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End RENAME3res.

Module LINK3args.
  Definition S := struct.decl [
    "File" :: Nfs_fh3.T;
    "Link" :: Diropargs3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End LINK3args.

Module LINK3resok.
  Definition S := struct.decl [
    "File_attributes" :: Post_op_attr.T;
    "Linkdir_wcc" :: Wcc_data.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End LINK3resok.

Module LINK3resfail.
  Definition S := struct.decl [
    "File_attributes" :: Post_op_attr.T;
    "Linkdir_wcc" :: Wcc_data.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End LINK3resfail.

Module LINK3res.
  Definition S := struct.decl [
    "Status" :: Nfsstat3;
    "Resok" :: LINK3resok.T;
    "Resfail" :: LINK3resfail.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End LINK3res.

Module READDIR3args.
  Definition S := struct.decl [
    "Dir" :: Nfs_fh3.T;
    "Cookie" :: Cookie3;
    "Cookieverf" :: Cookieverf3;
    "Count" :: Count3
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End READDIR3args.

Module Entry3.
  Definition S := struct.decl [
    "Fileid" :: Fileid3;
    "Name" :: Filename3;
    "Cookie" :: Cookie3;
    "Nextentry" :: struct.ptrT Entry3.S
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Entry3.

Module Dirlist3.
  Definition S := struct.decl [
    "Entries" :: struct.ptrT Entry3.S;
    "Eof" :: boolT
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Dirlist3.

Module READDIR3resok.
  Definition S := struct.decl [
    "Dir_attributes" :: Post_op_attr.T;
    "Cookieverf" :: Cookieverf3;
    "Reply" :: Dirlist3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End READDIR3resok.

Module READDIR3resfail.
  Definition S := struct.decl [
    "Dir_attributes" :: Post_op_attr.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End READDIR3resfail.

Module READDIR3res.
  Definition S := struct.decl [
    "Status" :: Nfsstat3;
    "Resok" :: READDIR3resok.T;
    "Resfail" :: READDIR3resfail.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End READDIR3res.

Module READDIRPLUS3args.
  Definition S := struct.decl [
    "Dir" :: Nfs_fh3.T;
    "Cookie" :: Cookie3;
    "Cookieverf" :: Cookieverf3;
    "Dircount" :: Count3;
    "Maxcount" :: Count3
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End READDIRPLUS3args.

Module Entryplus3.
  Definition S := struct.decl [
    "Fileid" :: Fileid3;
    "Name" :: Filename3;
    "Cookie" :: Cookie3;
    "Name_attributes" :: Post_op_attr.T;
    "Name_handle" :: Post_op_fh3.T;
    "Nextentry" :: struct.ptrT Entryplus3.S
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Entryplus3.

Module Dirlistplus3.
  Definition S := struct.decl [
    "Entries" :: struct.ptrT Entryplus3.S;
    "Eof" :: boolT
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Dirlistplus3.

Module READDIRPLUS3resok.
  Definition S := struct.decl [
    "Dir_attributes" :: Post_op_attr.T;
    "Cookieverf" :: Cookieverf3;
    "Reply" :: Dirlistplus3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End READDIRPLUS3resok.

Module READDIRPLUS3resfail.
  Definition S := struct.decl [
    "Dir_attributes" :: Post_op_attr.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End READDIRPLUS3resfail.

Module READDIRPLUS3res.
  Definition S := struct.decl [
    "Status" :: Nfsstat3;
    "Resok" :: READDIRPLUS3resok.T;
    "Resfail" :: READDIRPLUS3resfail.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End READDIRPLUS3res.

Module FSSTAT3args.
  Definition S := struct.decl [
    "Fsroot" :: Nfs_fh3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End FSSTAT3args.

Module FSSTAT3resok.
  Definition S := struct.decl [
    "Obj_attributes" :: Post_op_attr.T;
    "Tbytes" :: Size3;
    "Fbytes" :: Size3;
    "Abytes" :: Size3;
    "Tfiles" :: Size3;
    "Ffiles" :: Size3;
    "Afiles" :: Size3;
    "Invarsec" :: Uint32
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End FSSTAT3resok.

Module FSSTAT3resfail.
  Definition S := struct.decl [
    "Obj_attributes" :: Post_op_attr.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End FSSTAT3resfail.

Module FSSTAT3res.
  Definition S := struct.decl [
    "Status" :: Nfsstat3;
    "Resok" :: FSSTAT3resok.T;
    "Resfail" :: FSSTAT3resfail.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End FSSTAT3res.

Definition FSF3_LINK : expr := #(U32 1).

Definition FSF3_SYMLINK : expr := #(U32 2).

Definition FSF3_HOMOGENEOUS : expr := #(U32 8).

Definition FSF3_CANSETTIME : expr := #(U32 16).

Module FSINFO3args.
  Definition S := struct.decl [
    "Fsroot" :: Nfs_fh3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End FSINFO3args.

Module FSINFO3resok.
  Definition S := struct.decl [
    "Obj_attributes" :: Post_op_attr.T;
    "Rtmax" :: Uint32;
    "Rtpref" :: Uint32;
    "Rtmult" :: Uint32;
    "Wtmax" :: Uint32;
    "Wtpref" :: Uint32;
    "Wtmult" :: Uint32;
    "Dtpref" :: Uint32;
    "Maxfilesize" :: Size3;
    "Time_delta" :: Nfstime3.T;
    "Properties" :: Uint32
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End FSINFO3resok.

Module FSINFO3resfail.
  Definition S := struct.decl [
    "Obj_attributes" :: Post_op_attr.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End FSINFO3resfail.

Module FSINFO3res.
  Definition S := struct.decl [
    "Status" :: Nfsstat3;
    "Resok" :: FSINFO3resok.T;
    "Resfail" :: FSINFO3resfail.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End FSINFO3res.

Module PATHCONF3args.
  Definition S := struct.decl [
    "Object" :: Nfs_fh3.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End PATHCONF3args.

Module PATHCONF3resok.
  Definition S := struct.decl [
    "Obj_attributes" :: Post_op_attr.T;
    "Linkmax" :: Uint32;
    "Name_max" :: Uint32;
    "No_trunc" :: boolT;
    "Chown_restricted" :: boolT;
    "Case_insensitive" :: boolT;
    "Case_preserving" :: boolT
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End PATHCONF3resok.

Module PATHCONF3resfail.
  Definition S := struct.decl [
    "Obj_attributes" :: Post_op_attr.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End PATHCONF3resfail.

Module PATHCONF3res.
  Definition S := struct.decl [
    "Status" :: Nfsstat3;
    "Resok" :: PATHCONF3resok.T;
    "Resfail" :: PATHCONF3resfail.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End PATHCONF3res.

Module COMMIT3args.
  Definition S := struct.decl [
    "File" :: Nfs_fh3.T;
    "Offset" :: Offset3;
    "Count" :: Count3
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End COMMIT3args.

Module COMMIT3resok.
  Definition S := struct.decl [
    "File_wcc" :: Wcc_data.T;
    "Verf" :: Writeverf3
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End COMMIT3resok.

Module COMMIT3resfail.
  Definition S := struct.decl [
    "File_wcc" :: Wcc_data.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End COMMIT3resfail.

Module COMMIT3res.
  Definition S := struct.decl [
    "Status" :: Nfsstat3;
    "Resok" :: COMMIT3resok.T;
    "Resfail" :: COMMIT3resfail.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End COMMIT3res.

Definition MNTPATHLEN3 : expr := #(U32 1024).

Definition MNTNAMLEN3 : expr := #(U32 255).

Definition FHSIZE3 : expr := #(U32 64).

Definition Fhandle3: ty := slice.T byteT.

Definition Dirpath3: ty := stringT.

Definition Name3: ty := stringT.

Definition Mountstat3: ty := uint32T.

Definition MNT3_OK : expr := #0.

Definition MNT3ERR_PERM : expr := #1.

Definition MNT3ERR_NOENT : expr := #2.

Definition MNT3ERR_IO : expr := #5.

Definition MNT3ERR_ACCES : expr := #13.

Definition MNT3ERR_NOTDIR : expr := #20.

Definition MNT3ERR_INVAL : expr := #22.

Definition MNT3ERR_NAMETOOLONG : expr := #63.

Definition MNT3ERR_NOTSUPP : expr := #10004.

Definition MNT3ERR_SERVERFAULT : expr := #10006.

Definition MOUNT_PROGRAM : expr := #(U32 100005).

Definition MOUNT_V3 : expr := #(U32 3).

Definition MOUNTPROC3_NULL : expr := #(U32 0).

Definition MOUNTPROC3_MNT : expr := #(U32 1).

Definition MOUNTPROC3_DUMP : expr := #(U32 2).

Definition MOUNTPROC3_UMNT : expr := #(U32 3).

Definition MOUNTPROC3_UMNTALL : expr := #(U32 4).

Definition MOUNTPROC3_EXPORT : expr := #(U32 5).

Module Mountres3_ok.
  Definition S := struct.decl [
    "Fhandle" :: Fhandle3;
    "Auth_flavors" :: slice.T uint32T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Mountres3_ok.

Module Mountres3.
  Definition S := struct.decl [
    "Fhs_status" :: Mountstat3;
    "Mountinfo" :: Mountres3_ok.T
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Mountres3.

Module Mount3.
  Definition S := struct.decl [
    "Ml_hostname" :: Name3;
    "Ml_directory" :: Dirpath3;
    "Ml_next" :: struct.ptrT Mount3.S
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Mount3.

Module Mountopt3.
  Definition S := struct.decl [
    "P" :: struct.ptrT Mount3.S
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Mountopt3.

Module Groups3.
  Definition S := struct.decl [
    "Gr_name" :: Name3;
    "Gr_next" :: struct.ptrT Groups3.S
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Groups3.

Module Exports3.
  Definition S := struct.decl [
    "Ex_dir" :: Dirpath3;
    "Ex_groups" :: struct.ptrT Groups3.S;
    "Ex_next" :: struct.ptrT Exports3.S
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Exports3.

Module Exportsopt3.
  Definition S := struct.decl [
    "P" :: struct.ptrT Exports3.S
  ].
  Definition T: ty := struct.t S.
  Definition Ptr: ty := struct.ptrT S.
  Section fields.
    Context `{ext_ty: ext_types}.
    Definition get := struct.get S.
  End fields.
End Exportsopt3.
