(* autogenerated from github.com/goose-lang/goose/testdata/examples/comments *)
From New.golang Require Import defn.

Section code.
Context `{ffi_syntax}.

Definition ONE : expr := #(W64 1).

Definition TWO : expr := #(W64 2).

Definition Foo : go_type := structT [
  "a" :: boolT
].

Definition Foo__mset : list (go_string * val) := [
].

Definition Foo__mset_ptr : list (go_string * val) := [
].

Definition pkg_name' : go_string := "github.com/goose-lang/goose/testdata/examples/comments".

Definition define' : val :=
  rec: "define'" <> :=
    exception_do (do:  #()).

Definition initialize' : val :=
  rec: "initialize'" <> :=
    globals.package_init pkg_name' (λ: <>,
      exception_do (do:  (define' #()))
      ).

End code.
