(* autogenerated from github.com/goose-lang/goose/testdata/examples/import *)
From New.golang Require Import defn.
Require Import New.code.sync.atomic.

Definition example : go_string := "github.com/goose-lang/goose/testdata/examples/import".

Module example.
Section code.
Context `{ffi_syntax}.


Definition vars' : list (go_string * go_type) := [].

Definition functions' : list (go_string * val) := [].

Definition msets' : list (go_string * (list (go_string * val))) := [].

#[global] Instance info' : PkgInfo import.example :=
  {|
    pkg_vars := vars';
    pkg_functions := functions';
    pkg_msets := msets';
    pkg_imported_pkgs := [atomic];
  |}.

Definition initialize' : val :=
  rec: "initialize'" <> :=
    globals.package_init import.example (λ: <>,
      exception_do (do:  atomic.initialize')
      ).

End code.
End example.
