(* autogenerated from github.com/goose-lang/goose/testdata/examples/import *)
From New.golang Require Import defn.
Require Import New.code.sync.atomic.

Module example.
Section code.
Context `{ffi_syntax}.


Definition pkg_name' : go_string := "github.com/goose-lang/goose/testdata/examples/import".

Definition vars' : list (go_string * go_type) := [].

Definition functions' : list (go_string * val) := [].

Definition msets' : list (go_string * (list (go_string * val))) := [].

Definition initialize' : val :=
  rec: "initialize'" <> :=
    globals.package_init pkg_name' vars' functions' msets' (λ: <>,
      exception_do (do:  atomic.initialize')
      ).

End code.
End example.
