(* autogenerated from append_log *)
From Perennial.goose_lang Require Import prelude.
From Perennial.goose_lang Require Import ffi.disk_prelude.

From Goose Require github_com.tchajed.marshal.

(* Append-only, sequential, crash-safe log.

   The main interesting feature is that the log supports multi-block atomic
   appends, which are implemented by atomically updating an on-disk header with
   the number of valid blocks in the log. *)

Module Log.
  Definition S := struct.decl [
    "sz" :: uint64T;
    "diskSz" :: uint64T
  ].
End Log.

Definition Log__mkHdr: val :=
  λ: "log",
    let: "enc" := marshal.NewEnc disk.BlockSize in
    marshal.Enc__PutInt "enc" (struct.get Log.S "sz" "log");;
    marshal.Enc__PutInt "enc" (struct.get Log.S "diskSz" "log");;
    marshal.Enc__Finish "enc".
Theorem Log__mkHdr_t: ⊢ Log__mkHdr : (struct.t Log.S -> disk.blockT).
Proof. typecheck. Qed.
Hint Resolve Log__mkHdr_t : types.

Definition Log__writeHdr: val :=
  λ: "log",
    disk.Write #0 (Log__mkHdr "log").
Theorem Log__writeHdr_t: ⊢ Log__writeHdr : (struct.t Log.S -> unitT).
Proof. typecheck. Qed.
Hint Resolve Log__writeHdr_t : types.

Definition Init: val :=
  λ: "diskSz",
    (if: "diskSz" < #1
    then
      (struct.mk Log.S [
         "sz" ::= #0;
         "diskSz" ::= #0
       ], #false)
    else
      let: "log" := struct.mk Log.S [
        "sz" ::= #0;
        "diskSz" ::= "diskSz"
      ] in
      Log__writeHdr "log";;
      ("log", #true)).
Theorem Init_t: ⊢ Init : (uint64T -> (struct.t Log.S * boolT)).
Proof. typecheck. Qed.
Hint Resolve Init_t : types.

Definition Open: val :=
  λ: <>,
    let: "hdr" := disk.Read #0 in
    let: "dec" := marshal.NewDec "hdr" in
    let: "sz" := marshal.Dec__GetInt "dec" in
    let: "diskSz" := marshal.Dec__GetInt "dec" in
    struct.mk Log.S [
      "sz" ::= "sz";
      "diskSz" ::= "diskSz"
    ].
Theorem Open_t: ⊢ Open : (unitT -> struct.t Log.S).
Proof. typecheck. Qed.
Hint Resolve Open_t : types.

Definition Log__Get: val :=
  λ: "log" "i",
    let: "sz" := struct.get Log.S "sz" "log" in
    (if: "i" < "sz"
    then (disk.Read (#1 + "i"), #true)
    else (slice.nil, #false)).
Theorem Log__Get_t: ⊢ Log__Get : (struct.t Log.S -> uint64T -> (disk.blockT * boolT)).
Proof. typecheck. Qed.
Hint Resolve Log__Get_t : types.

Definition writeAll: val :=
  λ: "bks" "off",
    ForSlice (slice.T byteT) "i" "bk" "bks"
      (disk.Write ("off" + "i") "bk").
Theorem writeAll_t: ⊢ writeAll : (slice.T disk.blockT -> uint64T -> unitT).
Proof. typecheck. Qed.
Hint Resolve writeAll_t : types.

Definition Log__Append: val :=
  λ: "log" "bks",
    let: "sz" := struct.loadF Log.S "sz" "log" in
    (if: slice.len "bks" ≥ struct.loadF Log.S "diskSz" "log" - #1 - "sz"
    then #false
    else
      writeAll "bks" (#1 + "sz");;
      let: "newLog" := struct.mk Log.S [
        "sz" ::= "sz" + slice.len "bks";
        "diskSz" ::= struct.loadF Log.S "diskSz" "log"
      ] in
      Log__writeHdr "newLog";;
      struct.store Log.S "log" "newLog";;
      #true).
Theorem Log__Append_t: ⊢ Log__Append : (struct.ptrT Log.S -> slice.T disk.blockT -> boolT).
Proof. typecheck. Qed.
Hint Resolve Log__Append_t : types.

Definition Log__Reset: val :=
  λ: "log",
    let: "newLog" := struct.mk Log.S [
      "sz" ::= #0;
      "diskSz" ::= struct.loadF Log.S "diskSz" "log"
    ] in
    Log__writeHdr "newLog";;
    struct.store Log.S "log" "newLog".
Theorem Log__Reset_t: ⊢ Log__Reset : (struct.ptrT Log.S -> unitT).
Proof. typecheck. Qed.
Hint Resolve Log__Reset_t : types.
