name: CI

on:
  push:
    branches:
      - master
      - "*"
  pull_request:
  schedule:
    - cron: '0 8 * * 6'

jobs:
  test:
    strategy:
      matrix:
        go-version: ["1.22.x"]
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Check style
        run: |
          gofmt -w -s .
          go generate ./...
          git diff --exit-code
      - name: Go tests
        run: |
          go vet ./...
          go test -v ./...
      - name: End-to-end CLI tests
        run: |
          ./test/bats/bin/bats ./test/goose.bats
